package org.sikuli.script;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author rhocke
 */
public class KeyBoardSetupWindow extends javax.swing.JPanel {

  private String[] result = null;

  /**
   * Creates new form KeyBoardSetupWindow
   */
  public KeyBoardSetupWindow(String[] res) {
    result = res;
    initComponents();
  }

  public void setLogo(ImageIcon img) {
    logo.setIcon(img);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    logo = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    keyBoardText = new javax.swing.JTextArea();

    logo.setText("logo");
    logo.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        logoMouseClicked(evt);
      }
    });

    jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
    jLabel2.setText("Sikuli KeyBoard Setup");

    keyBoardText.setColumns(20);
    keyBoardText.setRows(5);
    jScrollPane1.setViewportView(keyBoardText);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jScrollPane1)
          .add(layout.createSequentialGroup()
            .add(logo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
            .add(jLabel2)
            .add(0, 6, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(logo)
          .add(jLabel2))
        .add(18, 18, 18)
        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 390, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(31, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
    result[0] = keyBoardText.getText();
  }//GEN-LAST:event_logoMouseClicked

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea keyBoardText;
  private javax.swing.JLabel logo;
  // End of variables declaration//GEN-END:variables

}
