nppp = App(r"c:\Program Files (x86)\Notepad++\notepad++.exe")
nb = App("IDE")
gc = App("chrome")
nppp.open(); wait(2)
gc.focus(); wait(1)
type("n",Key.CTRL)
nb.focus(); wait(2)
nppp.focus(); wait(2)
nppp.close()
gc.focus(); wait(1)
type("w",Key.CTRL)