#!/bin/sh
base=`pwd`
echo SourceBase $base

mrepo=~/.m2/repository/org/sikuli

setup=Basics
jython=Jython
api=API
ide=IDE

dist=$base/../Build
if [ -e $dist ]; then
  rm -f -R $dist
fi
mkdir $dist 

log=$dist/log.txt

echo "--- creating version info"
echo "--- creating version info" >$log
cd $base/$setup
mvn clean compile >>$log
version=`java -cp $base/$setup/target/classes org.sikuli.basics.RunSetup version`
mversion=`java -cp $base/$setup/target/classes org.sikuli.basics.RunSetup majorversion`
uversion=`java -cp $base/$setup/target/classes org.sikuli.basics.RunSetup updateversion`

echo --- version --- $version
echo --- major version --- $mversion
echo --- update version --- $uversion
echo --- version --- $version >>$log
echo --- major version --- $mversion >>$log
echo --- update version --- $uversion >>$log

# ----------- Basics
echo --- Basics timestamp
echo --- BUILD Basics timestamp >>$log
cd $base/$setup
src=$base/$setup/src/main/java/org/sikuli/basics/RunSetup.java
out=$base/$setup/src/main/java/org/sikuli/basics/RunSetupX.java
xdd=`date`
sed "s/##--##.*##--##/##--##$xdd##--##/" $src >$out
mv -f $out $src
mvn install >>$log
# ----------- Setup
echo --- make Setup
cd $base
mvn -f Basics/setup* >>$log
cp Basics/target-setup/sikulixsetup*.jar $dist/sikulixsetup-$mversion.jar

if [ "$1" != "setup" ]; then
  # ----------- API
  echo --- make API
  cd $base
  mvn -f API/api* >>$log
  cp API/target-api/*api-plain.jar $dist/$version-2.jar
  
  # ----------- SikuliX
  echo --- make SikuliX
  cd $base
  mvn -f IDE/ide* >>$log
  cp IDE/target-ide/*ide-plain.jar $dist/$version-1.jar
  
  # ----------- MacApp
  echo --- make MacApp
  cd $base
  cp MacApp/target/*.jar $dist
  
  # ----------- Tesseract
  echo --- make Tesseract
  cd $base
  cp Tesseract/target/*.jar $dist  
  
  # ----------- Remote
  echo --- make Remote
  cd $base
  cp Remote/target/*.jar $dist/$version-3.jar  
fi
grep -i BUILD $log
