#!/bin/sh
source=Setup/target
base=`pwd`
dist=$base/../SikuliX-Setup
if [ -e $dist ]; then
  rm -f -R $dist
fi
mkdir $dist
mkdir $dist/Downloads

echo ----- collecting jars
cd $source
jar=`ls *-plain.jar`
version=`java -jar $jar pversion`
uversion=`java -jar $jar uversion`
echo ----- for version $version
java -Dsikuli.Debug=3 -jar sikulixsetup-$version-plain.jar noSetup
cd $base
ls -l $source

echo ----- copy Setup
cp $source/sikulixsetup-$version-plain.jar $dist/sikulixsetup-$uversion.jar
ls -l $dist

echo ----- copy Jars
cp $source/Downloads/* $dist/Downloads
ls -l $dist/Downloads
