#!/bin/sh
# creates the javadocs for selected classes and their public members
version=1.1.0
apijar=API/target/SikuliX-API-$version.jar
basicsjar=Basics/target/SikuliX-Basics-$version.jar
nativesjar=Natives/target/SikuliX-Natives-$version.jar
opencvjar=OpenCV4Sikulix/target/OpenCV4Sikulix-2.4.8.jar
apisrc=API/src/main/java/org/sikuli/script
basicssrc=Basics/src/main/java/org/sikuli/basics
echo $apisrc/Region.java >createJavadocsClasses
echo $apisrc/FindFailed.java >>createJavadocsClasses
echo $apisrc/Match.java >>createJavadocsClasses
echo $apisrc/Screen.java >>createJavadocsClasses
echo $apisrc/Pattern.java >>createJavadocsClasses
echo $apisrc/Location.java >>createJavadocsClasses
echo $apisrc/Image.java >>createJavadocsClasses
echo $apisrc/ImagePath.java >>createJavadocsClasses
echo $apisrc/ImageGroup.java >>createJavadocsClasses
echo $apisrc/ScreenImage.java >>createJavadocsClasses
echo $apisrc/Finder.java >>createJavadocsClasses
echo $apisrc/ImageFinder.java >>createJavadocsClasses
echo $apisrc/ImageFind.java >>createJavadocsClasses
echo $apisrc/Mouse.java >>createJavadocsClasses
echo $apisrc/Button.java >>createJavadocsClasses
echo $apisrc/Key.java >>createJavadocsClasses
echo $apisrc/ObserverCallBack.java >>createJavadocsClasses
echo $apisrc/ObserveEvent.java >>createJavadocsClasses
echo $apisrc/App.java >>createJavadocsClasses
echo $apisrc/Env.java >>createJavadocsClasses
echo $basicssrc/Settings.java >>createJavadocsClasses
echo $basicssrc/Debug.java >>createJavadocsClasses
javadoc -public -classpath $apijar:$basicsjar:$nativesjar:$opencvjar -d target/docs @createJavadocsClasses
