switchApp("textedit")
write("#M.a#R.#W1.")
write("#W1.#M.#UP.")
write("#S+#M.#R.#S-")
write("#M.c")
print App.getClipboard()
write("#D.#D.")
write("#S+#M.#R.#S-")
write("#M.c")
print App.getClipboard()
wait(3)