#!/bin/sh
base=`pwd`
echo -
echo ---

if [ "$sbase" == "" ]; then
	source=$base/Setup/target
	dist=$base/Setup/target/Setup
  target=$base/SikuliX-Setup
else
  echo ----- running on Jenkins
  source=$sbase/Setup/target
	dist=$sbase/Setup/target/Setup
  target=$jbase/SikuliX-Setup
  isjenkins=true
fi

echo ----- SikuliX collecting jars in $base
if [ -e $dist ]; then
  rm -f *.jar
  rm -f -R $dist/Downloads
fi
mkdir $dist/Downloads
if [ -e $target ]; then
  rm -f -R $target
fi
mkdir $target
mkdir $target/Downloads

# ----------- Setup
echo ----- collecting jars
setupjar=`ls $source/*-plain.jar`
pversion=`java -jar $setupjar pversion`
java -jar $setupjar noSetup
echo ----- content of $dist
ls -l $dist
ls -l $dist/Downloads

# ----------- Setup
echo ----- copy Setup
cp $dist/*.jar $target/

# ----------- Jars
echo ----- copy Jars
cp $dist/Downloads/* $target/Downloads/

echo ----------- final content of $target
ls -l $target
ls -l $target/Downloads
echo ----------- SikuliX collectjars end -----------
if [ "$isjenkins" == "" ]; then
	echo -
	echo --
	echo ----
	echo ------
	echo -------- If it looks like success -----------
	echo ... move the folder $target
	echo to where you want
	echo and name it as you like
	echo and run setup, to get your wanted packages.
	echo !! BE SURE, not to download anything !!
	echo !! You are doing an offline setup !!
	echo ---------------------------------------------
fi
